WebsiteBanHang/Areas/User/Controllers/HangSanXuatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Areas.User.Models;
using PagedList;

namespace WebsiteBanHang.Areas.User.Controllers
{
    public class HangSanXuatController : Controller
    {
        // GET: User/HangSanXuat
        LaptopModel db = new LaptopModel();
        public ActionResult PatialHangLaptop()
        {
            return View(db.HangSX.ToList());
        }

        public ActionResult XemHangSanXuat(int MaHang = 0, int PageNum = 1, int PageSize = 6)
        {
            List<SanPham> lstlap = db.SanPham.Where(x => x.MaHangSX == MaHang).OrderBy(n => n.GiaBan).ToList();
            ViewBag.Mh = MaHang;
            return View(lstlap.ToPagedList(PageNum, PageSize));
        }
    }
}

WebsiteBanHang/Areas/User/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Areas.User.Models;


namespace WebsiteBanHang.Areas.User.Controllers
{
    public class HomeController : Controller
    {
        // GET: User/Home
       
        public ActionResult Index()
        {
            return View();
        }
     
    }
}

WebsiteBanHang/Areas/User/Controllers/LaptopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Areas.User.Models;
using PagedList;

namespace WebsiteBanHang.Areas.User.Controllers
{
    public class LaptopController : Controller
    {
        // GET: User/Laptop
        LaptopModel db = new LaptopModel();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PatialSanPhamMoi()
        {
            var lstLaptopMoi = db.SanPham.Take(6).ToList();
            return View(lstLaptopMoi);
        }
/*        public ActionResult PatialFullSanPham(int PageNum = 1, int PageSize = 12)
        {
            var lstLaptop = db.SanPham.OrderBy(n => n.MaLap);
            return View(lstLaptop.ToPagedList(PageNum, PageSize));
        }*/
        public ActionResult PatialFullSanPham()
        {
            var lstLaptop = db.SanPham.Take(12).ToList();
            return View(lstLaptop);
        }
        public ActionResult XemChiTiet(int malap = 0)
        {
            SanPham Chitiet = db.SanPham.SingleOrDefault(n => n.MaLap == malap);
            if(Chitiet == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(Chitiet);
        }

    }
}

WebsiteBanHang/Areas/User/Controllers/LoaiLaptopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Areas.User.Models;
using PagedList;
using PagedList.Mvc;
namespace WebsiteBanHang.Areas.User.Controllers
{
    public class LoaiLaptopController : Controller
    {
        // GET: User/LoaiLaptop
        LaptopModel db = new LaptopModel();
        public ActionResult PatialLoaiLaptop()
        {

            return View(db.TheLoai.ToList());
        }
        /*        public ActionResult XemLoaiLap(int Maloai = 0)
                {
                    List<SanPham> lstLap = db.SanPham.Where(x => x.MaLoai == Maloai).Take(12).OrderBy(x => x.GiaBan).ToList();

                    return View(lstLap);

                }*/
        public ActionResult XemLoaiLap(int Maloai = 0, int PageNum = 1, int PageSize = 5)
        {
            IQueryable<SanPham>  lstLap = db.SanPham.Where(x => x.MaLoai == Maloai).OrderBy(n => n.MaLap);
            ViewBag.Ml = Maloai;
            return View(lstLap.ToPagedList(PageNum,PageSize));

        }

    }
}

WebsiteBanHang/Areas/User/Views/Home/Index.cshtml
@{
    Layout = "~/Areas/User/Views/Layout/NguoiDungLayout.cshtml";
    ViewBag.Title = "Index";
}


<div class="slider-area">
    <!-- Slider -->
    <div class="block-slider block-slider4">
        <ul class="" id="bxslider-home4">
            <li>
                <img src="~/Areas/User/Content/img/h4-slide.png" alt="Slide">
                <div class="caption-group">
                    <h2 class="caption title">
                        iPhone <span class="primary">6 <strong>Plus</strong></span>
                    </h2>
                    <h4 class="caption subtitle">Dual SIM</h4>
                    <a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
                </div>
            </li>
            <li>
                <img src="~/Areas/User/Content/img/h4-slide2.png" alt="Slide">
                <div class="caption-group">
                    <h2 class="caption title">
                        by one, get one <span class="primary">50% <strong>off</strong></span>
                    </h2>
                    <h4 class="caption subtitle">school supplies & backpacks.*</h4>
                    <a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
                </div>
            </li>
            <li>
                <img src="~/Areas/User/Content/img/h4-slide3.png" alt="Slide">
                <div class="caption-group">
                    <h2 class="caption title">
                        Apple <span class="primary">Store <strong>Ipod</strong></span>
                    </h2>
                    <h4 class="caption subtitle">Select Item</h4>
                    <a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
                </div>
            </li>
            <li>
                <img src="~/Areas/User/Content/img/h4-slide4.png" alt="Slide">
                <div class="caption-group">
                    <h2 class="caption title">
                        Apple <span class="primary">Store <strong>Ipod</strong></span>
                    </h2>
                    <h4 class="caption subtitle">& Phone</h4>
                    <a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
                </div>
            </li>
        </ul>
    </div>
    <!-- ./Slider -->
</div> <!-- End slider area -->
@* Chen vao partial the loai laptop*@
@Html.Action("PatialLoaiLaptop", "LoaiLaptop");

<div class="maincontent-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="latest-product">
                    @* Chèn vào partial view sản phẩm mới  *@
                    @Html.Action("PatialSanPhamMoi", "Laptop");
                </div>
            </div>
        </div>
    </div>
</div> <!-- End main content area -->

<div class="brands-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            @* Patial hang laptop*@
            @Html.Action("PatialHangLaptop", "HangSanXuat");
        </div>
    </div>
</div> <!-- End brands area -->

@Html.Action("PatialFullSanPham", "Laptop");